# Generated by Django 3.2 on 2022-08-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bug_class', models.CharField(max_length=255)),
                ('payload', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'payload',
            },
        ),
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reward', models.IntegerField(blank=True, null=True)),
                ('hunter', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounties', to='backend.payload')),
            ],
            options={
                'db_table': 'bounty',
            },
        ),
    ]
